openapi: 3.0.1
info:
  title: My Microservice
  version: 1.0.0

paths:
  /users:
    get:
      summary: Get all users
      x-handler: userHandler.getAllUsers
      x-authorization: true
      responses:
        '200':
          description: List of users
